server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: player-service
          uri: lb://player-service
          predicates:
            - Path=/api/players/**
          filters:
            - name: CircuitBreaker
              args:
                name: player-service
                fallbackUri: forward:/fallback/players
        - id: team-service
          uri: lb://team-service
          predicates:
            - Path=/api/teams/**
          filters:
            - name: CircuitBreaker
              args:
                name: team-service
                fallbackUri: forward:/fallback/teams
        - id: match-service
          uri: lb://match-service
          predicates:
            - Path=/api/matches/**
          filters:
            - name: CircuitBreaker
              args:
                name: match-service
                fallbackUri: forward:/fallback/matches
        - id: statistics-service
          uri: lb://statistics-service
          predicates:
            - Path=/api/statistics/**
          filters:
            - name: CircuitBreaker
              args:
                name: statistics-service
                fallbackUri: forward:/fallback/statistics
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway

resilience4j:
  circuitbreaker:
    instances:
      player-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
      team-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
      match-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10
      statistics-service:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        sliding-window-size: 10

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG