apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: cricket-system
  labels:
    app: api-gateway
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: api-gateway
  type: LoadBalancer