apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: cricket-system
  labels:
    app: discovery-service
spec:
  ports:
  - port: 8761
    targetPort: 8761
  selector:
    app: discovery-service
  type: ClusterIP