apiVersion: v1
kind: Service
metadata:
  name: player-service
  namespace: cricket-system
  labels:
    app: player-service
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: player-service
  type: ClusterIP